# Site settings
title: Our wedding
email: k.sideris+wedding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This awesome site is devoted to the wedding of Kyriakos & Athanasia
  taking place at summer solstice of 2015 at <a href=https://goo.gl/maps/9Qlg3>Eupolis, Paiania, Greece</a>.

baseurl: "http://kyrsideris.github.io/wedding" # the subpath of your site, e.g. /blog/
url: "http://kyrsideris.github.io/wedding" # the base hostname & protocol for your site
twitter_username: kyrsideris
github_username:  kyrsideris

# Build settings
markdown: kramdown
